language: groovy
sudo: false
cache:
  directories:
    - $HOME/.gradle
notifications:
  email: false
jdk:
  - oraclejdk7
  - oraclejdk8
before_install:
  - chmod a+x gradlew
script: ./gradlew clean check
